# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qorCFzj2esrIaIJXRgvkKPjsoBMSyBHT
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import tensorflow as tf

df=pd.read_csv("/content/drive/MyDrive/project/cleaned_weather.csv")
df.head()

df.shape

df.columns

temp=df['T']
temp.plot()

def df_to_X_y(df, window_size):
    X, y = [], []
    df_as_np = df.to_numpy()
    for i in range(len(df_as_np) - window_size):
        row = df_as_np[i:i + window_size]  # Collect a window of size `window_size`
        X.append(row)
        label = df_as_np[i + window_size]  # Label corresponds to the next value
        y.append(label)
    return np.array(X), np.array(y)

WINDOW_SIZE = 5
X, y = df_to_X_y(temp, WINDOW_SIZE)
X.shape, y.shape

X

y

X_train, y_train = X[:40000], y[:40000]
X_val, y_val = X[40000:45000], y[40000:45000]
X_test, y_test = X[45000:], y[45000:]

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.optimizers import Adam

X_train.shape, y_train.shape

model1 = Sequential()
model1.add(InputLayer((5,1)))
model1.add(LSTM(64))
model1.add(Dense(8, 'relu'))
model1.add(Dense(1, 'linear'))

model1.summary()

cp = ModelCheckpoint('/kaggle/working/best_model.keras', save_best_only=True)
model1.compile(loss=MeanSquaredError(), optimizer=Adam(learning_rate=0.0001), metrics = [RootMeanSquaredError()])

model1.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=10, callbacks=[cp])

from tensorflow.keras.models import load_model

model1 = load_model('/kaggle/working/best_model.keras')

train_predictions = model1.predict(X_train).flatten()
train_results = pd.DataFrame(data={'Train Predictions':train_predictions, 'Actuals':y_train})
train_results

import matplotlib.pyplot as plt

plt.plot(train_results['Train Predictions'])
plt.plot(train_results['Actuals'])

plt.plot(train_results['Train Predictions'][:100])
plt.plot(train_results['Actuals'][:100])

val_predictions = model1.predict(X_val).flatten()
val_results = pd.DataFrame(data={'Val Predictions':val_predictions, 'Actuals':y_val})
val_results

plt.plot(val_results['Val Predictions'][:100])
plt.plot(val_results['Actuals'][:100])

test_predictions = model1.predict(X_test).flatten()
test_results = pd.DataFrame(data={'Test Predictions':test_predictions, 'Actuals':y_test})
test_results

plt.plot(test_results['Test Predictions'][:100])
plt.plot(test_results['Actuals'][:100])





